name: WordPress & PHP Compatibility Matrix

on:
  push:
    branches: [ main ]
  pull_request:
  # Allow manually triggering the workflow
  workflow_dispatch:
  # Run weekly to catch new compatibility issues
  schedule:
    - cron: '0 2 * * 1'  # Every Monday at 2 AM UTC

# Cancels all previous workflow runs for the same branch that have not yet completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  compatibility-test:
    name: WP ${{ matrix.wp-version }} / PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        wp-version: ['latest']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysqli, curl, zip, intl, gd, mbstring, fileinfo, xml
          coverage: none
          tools: composer:v2
      
      - name: Install Composer dependencies
        uses: ramsey/composer-install@3.1.1
        with:
          dependency-versions: highest
          composer-options: "--prefer-dist --no-progress"
      
      - name: WordPress Plugin Check
        uses: WordPress/plugin-check-action@v1.1.2
        with:
          build-dir: './'
          categories: |
            accessibility
            general
            performance
            plugin_repo
            security
          include-experimental: false
          ignore-warnings: false
          ignore-errors: false
          wp-version: ${{ matrix.wp-version }}
      
      - name: Create compatibility issue on failure
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          PHP_VERSION: ${{ matrix.php-version }}
          WP_VERSION: ${{ matrix.wp-version }}
        with:
          filename: .github/ISSUE_TEMPLATE/compatibility-test-failure.md
          update_existing: false
          
      - name: Mark job as failed after issue creation
        if: ${{ failure() }}
        run: |
          echo "::error::Compatibility test failed for WP ${{ matrix.wp-version }} / PHP ${{ matrix.php-version }}. Created issue for tracking."
          exit 1
